# Homework 2
## Matthew Eller
## Collaborator: Maggie Reed
## Time (hours): 4

#### #1. Rotate the 4-D array
    array4 = np.arange(36).reshape((2, 3, 2, 3))
    print(array4)

In [3]:
import numpy as np

array4 = np.arange(36).reshape((2, 3, 2, 3))
print(array4)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]]


#### Question 1. How will array4.T change the order of dimensions? Use the transpose method to get the same result as array4.T

In [4]:
print("array4.T")
print(array4.T) #array4.T permutes axes 1 and 2 and permutes 0 and 3 as (12)(03) in cycle notation
print("transpose method")
print(np.transpose(array4, (3,2,1,0))) #0-->3, 1-->2, 2-->1, and 3-->0 using transpose method
print("show they are equal arrays")
print(array4.T==np.transpose(array4, (3,2,1,0))) #check that both methods achieve equal result

array4.T
[[[[ 0 18]
   [ 6 24]
   [12 30]]

  [[ 3 21]
   [ 9 27]
   [15 33]]]


 [[[ 1 19]
   [ 7 25]
   [13 31]]

  [[ 4 22]
   [10 28]
   [16 34]]]


 [[[ 2 20]
   [ 8 26]
   [14 32]]

  [[ 5 23]
   [11 29]
   [17 35]]]]
transpose method
[[[[ 0 18]
   [ 6 24]
   [12 30]]

  [[ 3 21]
   [ 9 27]
   [15 33]]]


 [[[ 1 19]
   [ 7 25]
   [13 31]]

  [[ 4 22]
   [10 28]
   [16 34]]]


 [[[ 2 20]
   [ 8 26]
   [14 32]]

  [[ 5 23]
   [11 29]
   [17 35]]]]
show they are equal arrays
[[[[ True  True]
   [ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]
   [ True  True]]]


 [[[ True  True]
   [ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]
   [ True  True]]]


 [[[ True  True]
   [ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]
   [ True  True]]]]


#### Question 2. How will array4.swapaxes(1,2) change the order of dimensions? Use the transpose method to get the same result as array4.swapaxes(1,2).

In [10]:
print("swap axes method")
print(array4.swapaxes(1,2)) #swaps axes 1 and 2, does not change dimension of resulting array
print("transpose method")
print(np.transpose(array4,(0,2,1,3))) #transposes axes 1 and 2
print("show that they are equal arrays")
print(array4.swapaxes(1,2)==np.transpose(array4,(0,2,1,3))) #show resulting arrays have equal results

swap axes method
[[[[ 0  1  2]
   [ 6  7  8]
   [12 13 14]]

  [[ 3  4  5]
   [ 9 10 11]
   [15 16 17]]]


 [[[18 19 20]
   [24 25 26]
   [30 31 32]]

  [[21 22 23]
   [27 28 29]
   [33 34 35]]]]
transpose method
[[[[ 0  1  2]
   [ 6  7  8]
   [12 13 14]]

  [[ 3  4  5]
   [ 9 10 11]
   [15 16 17]]]


 [[[18 19 20]
   [24 25 26]
   [30 31 32]]

  [[21 22 23]
   [27 28 29]
   [33 34 35]]]]
show that they are equal arrays
[[[[ True  True  True]
   [ True  True  True]
   [ True  True  True]]

  [[ True  True  True]
   [ True  True  True]
   [ True  True  True]]]


 [[[ True  True  True]
   [ True  True  True]
   [ True  True  True]]

  [[ True  True  True]
   [ True  True  True]
   [ True  True  True]]]]


#### Question 3. Use the transpose method to generate the following result:
    [[[[ 0  6 12]
       [ 3  9 15]]
      [[18 24 30]
       [21 27 33]]]
     [[[ 1  7 13]
       [ 4 10 16]]
      [[19 25 31]
       [22 28 34]]]
     [[[ 2  8 14]
       [ 5 11 17]]
      [[20 26 32]
       [23 29 35]]]]

In [27]:
print("transpose method")
print(np.transpose(array4,(3,0,2,1))) # permute axes as 0-->1, 1-->3, 3-->0 or (013) as a cycle

transpose method
[[[[ 0  6 12]
   [ 3  9 15]]

  [[18 24 30]
   [21 27 33]]]


 [[[ 1  7 13]
   [ 4 10 16]]

  [[19 25 31]
   [22 28 34]]]


 [[[ 2  8 14]
   [ 5 11 17]]

  [[20 26 32]
   [23 29 35]]]]


#### #2.  The ndarray.argmin() and ndarray.argmax() methods can only return the index from a flat array, which means they unfold the n-dim array into 1-d array and return the 1-d index. For example, the following code will return 18. Now we want to obtain a tuple of indices which can be used to locate the minimum or maximum. Each element of the tuple is the index of minimum or maximum in the corresponding dimension. In the following example we want to find (4,2), so that array[4,2] will give the maximum.
       np.random.seed(10)
       array2 = np.random.randn(5, 4)
       print(array2)
       array2.argmax()
#### Please write two functions array_argmin(arr) and array_argmax(arr) where the input arr is an n-dim array, and the functions will return a tuple of n indices for the minimum and maximum respectively.

In [2]:
import numpy as np
np.random.seed(10) #seed at 10

print('~~**Please input an array size by typing in a whole real value for rows and columns**~~')

#propt for user input of number of rows and columns for array
rowx = int(input('Row: '))
coly = int(input('Column: '))
print("")

#create a random array using the seed from the user input
array2 = np.random.randn(rowx,coly)
print("The resulting random array is: ")
print("")
print(array2)
print("")

#define array_argmax function using array2 as input
#find the position where the max occurs, print position indice
def array_argmax(array2):
    return(np.where(array2==array2.max()))

#define array_argmin function using array2 as input
#find the position where the min occurs, print position indice
def array_argmin(array2):
    return(np.where(array2==array2.min()))


#prompt user for input as to whether they want to find the min or max value's position
#if input==0, return argmin
#if input==1, return argmax
print('~~**Type 0 for the indices of the minimum value and 1 for the maximum**~~')
print("")
select = int(input('0 or 1: '))

if select == 0:
    print("")
    print("The indices of the min value are: ", array_argmin(array2))
    
else:
    print("")
    print("The indices of the max value are: ", array_argmax(array2))

~~**Please input an array size by typing in a whole real value for rows and columns**~~
Row: 4
Column: 5

The resulting random array is: 

[[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597]
 [-0.72008556  0.26551159  0.10854853  0.00429143 -0.17460021]
 [ 0.43302619  1.20303737 -0.96506567  1.02827408  0.22863013]
 [ 0.44513761 -1.13660221  0.13513688  1.484537   -1.07980489]]

~~**Type 0 for the indices of the minimum value and 1 for the maximum**~~

0 or 1: 0

The indices of the min value are:  (array([0], dtype=int32), array([2], dtype=int32))


#### #3. Let X be a time series of 0's and 1's indicating the outcome of each trial (0 is failure, 1 is success). Write a function relative_freq(arr) where the input arr is a 1-d array of 0's and 1's. The function returns a 1-d array of the same size, of which each element is the relative frequency of success at the current time point. For example, X = [0,0,1,0,0,1,1,0,0,1] shows the result of 10 trials at time points 1,2,3,...,10. The function will find the relative frequency of success at each time point, i.e.p^=[0/1,0/2,1/3,1/4,1/5,2/6,3/7,3/8,3/9,4/10]
#### (Hint: use cumsum.)

In [3]:
import numpy as np

np.random.seed(10) #seed at 10
arr = np.random.choice(2,10) #creates a 1D array of ones and zeros
print(arr)

countarr = np.cumsum(arr) #sum cumulatively across arr array


def relative_freq(countarr):
    result = '' #initialize variable
    count = 1 #starting index of denominator
    
    for (index, k) in np.ndenumerate(countarr): 
        result = (result+str(k)+'/'+str(count)+' ')  #generates the relative frequency of success using string methods
        count = count + 1 #continues to move through counting the trial set
    print(result) #prints result to new array and continues
    
relative_freq(countarr)

[1 1 0 1 0 1 1 0 1 1]
1/1 2/2 2/3 3/4 3/5 4/6 5/7 5/8 6/9 7/10 
